name: Install Test

on:
    push:
    pull_request:

jobs:
    test-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4

            - uses: ruby/setup-ruby@v1
              with:
                ruby-version: "3.3"
            
            - name: Run Install Script
              shell: cmd
              run: .\install\install.bat

            - name: Make lat visible to later steps
              shell: bash
              run: echo "$USERPROFILE\\bin" >> "$GITHUB_PATH"
            
            - name: Compile a test file
              shell: cmd
              run: lat build test/fixtures/main.lat

            - name: Check Output exists
              shell: cmd
              run: if (-not (Test-Path .latc/main.lua)) { exit 1 }